"use client";

import { useEffect, useRef, useState } from "react";

type IconName = "home"|"check"|"calendar"|"wallet"|"user"|"plane"|"receipt"|"pin"|"arrow"|"bell"|"users"|"sparkle"|"upload"|"close"|"camera"|"hotel"|"map"|"cloud"|"download"|"shield"|"plus"|"edit";
type ModalType = "ticket"|"receipt"|null;

function Icon({name,size=22}:{name:IconName;size?:number}){
  const p:Record<IconName,React.ReactNode>={
    home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/></>,check:<path d="M5 12.5 9.2 17 19 7"/>,calendar:<><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18"/></>,wallet:<><path d="M4 6.5h14a2 2 0 0 1 2 2V19H4a2 2 0 0 1-2-2V6.5a2 2 0 0 1 2-2h12"/><path d="M15 12h7v4h-7a2 2 0 0 1 0-4Z"/></>,user:<><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></>,plane:<><path d="m3 11 18-7-7 18-3-7-8-4Z"/><path d="m11 15 4-4"/></>,receipt:<><path d="M5 3v18l3-2 4 2 4-2 3 2V3l-3 2-4-2-4 2-3-2Z"/><path d="M9 9h6M9 13h5"/></>,pin:<><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,arrow:<><path d="M5 12h14M14 7l5 5-5 5"/></>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4"/></>,users:<><circle cx="9" cy="8" r="3"/><path d="M3 19a6 6 0 0 1 12 0M16 5.5a3 3 0 0 1 0 5.8M18 14a5 5 0 0 1 3 5"/></>,sparkle:<><path d="m12 3 1.3 4.1L17 9l-3.7 1.9L12 15l-1.3-4.1L7 9l3.7-1.9L12 3ZM5 14l.7 2.3L8 17.5l-2.3 1.2L5 21l-.7-2.3L2 17.5l2.3-1.2L5 14Z"/></>,upload:<><path d="M12 16V4M7 9l5-5 5 5"/><path d="M4 15v5h16v-5"/></>,close:<><path d="m6 6 12 12M18 6 6 18"/></>,camera:<><path d="M4 7h3l2-3h6l2 3h3v13H4V7Z"/><circle cx="12" cy="13" r="4"/></>,hotel:<><path d="M4 21V5h10v16M14 10h6v11M8 9h2M8 13h2M8 17h2M17 14h1M17 17h1M2 21h20"/></>,map:<><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Z"/><path d="M9 3v15M15 6v15"/></>,cloud:<><path d="M7 18h11a4 4 0 0 0 0-8 6 6 0 0 0-11.3-2A5 5 0 0 0 7 18Z"/></>,download:<><path d="M12 4v12M7 11l5 5 5-5M4 20h16"/></>,shield:<><path d="M12 3 20 6v6c0 5-3.4 8-8 10-4.6-2-8-5-8-10V6l8-3Z"/><path d="m9 12 2 2 4-4"/></>,plus:<><path d="M12 5v14M5 12h14"/></>,edit:<><path d="m4 20 4-.8L19 8.3 15.7 5 4.8 15.9 4 20ZM14.5 6.2l3.3 3.3"/></>};
  return <svg aria-hidden="true" viewBox="0 0 24 24" width={size} height={size} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>;
}

const itinerary=[{time:"09:30",title:"築地場外市場",note:"由酒店步行 12 分鐘",type:"早餐",color:"coral"},{time:"12:00",title:"teamLab Borderless",note:"麻布台之丘・門票已儲存",type:"景點",color:"blue"},{time:"18:30",title:"銀座 鳥よし",note:"已預約 3 位・確認編號 8K21",type:"晚餐",color:"gold"}];

function Brand(){return <div className="brand-lockup"><div className="app-mark" aria-label="旅記 TripLog 圖示"><span className="case-handle"/><span className="case-body"><span className="case-tag"/></span><span className="mark-pin"><span/></span></div><div><p className="eyebrow">旅記</p><h1>TripLog</h1></div></div>}
function Timeline(){return <div className="timeline">{itinerary.map(i=><article className="timeline-item" key={i.time}><time>{i.time}</time><span className={`timeline-dot ${i.color}`}/><div><span className={`type-tag ${i.color}`}>{i.type}</span><h4>{i.title}</h4><p>{i.note}</p></div></article>)}</div>}

export default function Home(){
  const [active,setActive]=useState("首頁");const [notice,setNotice]=useState("");const [modal,setModal]=useState<ModalType>(null);const [picked,setPicked]=useState("");const fileRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{
    if("serviceWorker" in navigator){
      const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";
      navigator.serviceWorker.register(`${basePath}/sw.js`).catch(()=>undefined);
    }
  },[]);
  const toast=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(""),2200)};
  const pick=(type:ModalType)=>{setPicked("");setModal(type)};
  return <main className="app-shell"><div className="phone-app">
    <header className="topbar"><Brand/><button className="icon-button" aria-label="通知" onClick={()=>toast("目前沒有新通知")}><Icon name="bell" size={21}/><span className="notification-dot"/></button></header>

    {active==="首頁"&&<>
      <section className="greeting"><div><p>晚上好，Man Tat</p><h2>下一站，東京。</h2></div><span className="weather-pill">東京 · 24°C</span></section>
      <section className="trip-card"><div className="trip-card-top"><div><span className="trip-status">即將出發</span><h3>2026 東京之旅</h3><p>10月12日 — 10月18日 · 7日6夜</p></div><div className="countdown"><strong>50</strong><span>日後</span></div></div><div className="route-line"><span className="airport">HKG</span><span className="flight-line"><Icon name="plane" size={17}/></span><span className="airport">HND</span></div><div className="trip-meta"><span><Icon name="users" size={17}/>3 位同行者</span><span>預算餘額 <strong>HK$16,420</strong></span></div></section>
      <section className="quick-grid"><button className="quick-card primary" onClick={()=>pick("ticket")}><span className="quick-icon"><Icon name="plane"/></span><span><strong>上傳機票</strong><small>自動建立旅程</small></span><Icon name="arrow" size={18}/></button><button className="quick-card" onClick={()=>pick("receipt")}><span className="quick-icon receipt"><Icon name="receipt"/></span><span><strong>拍攝收據</strong><small>自動入帳分帳</small></span><Icon name="arrow" size={18}/></button></section>
      <section className="prep-card"><div className="section-heading"><div><p>出發前準備</p><h3>已完成 6 / 9 項</h3></div><button onClick={()=>setActive("準備")}>查看全部</button></div><div className="progress-track"><span style={{width:"67%"}}/></div><button className="prep-alert" onClick={()=>setActive("準備")}><span className="alert-icon"><Icon name="sparkle" size={19}/></span><span><strong>Visit Japan 尚未完成</strong><small>酒店及航班資料已準備好，可一鍵複製。</small></span><Icon name="arrow" size={18}/></button></section>
      <section className="day-section"><div className="section-heading day-heading"><div><p>10月13日・星期二</p><h3>東京第二日</h3></div><button className="recommend-button" onClick={()=>toast("找到酒店附近 18 個景點")}><Icon name="pin" size={16}/>附近推介</button></div><Timeline/></section>
    </>}

    {active==="準備"&&<section className="screen-content"><div className="page-title"><div><p>2026 東京之旅</p><h2>出發前準備</h2></div><span className="completion-ring">67%</span></div><div className="info-banner"><Icon name="shield"/><div><strong>入境要求已於今日核實</strong><p>適用於香港特區護照・旅遊7日</p></div></div><h3 className="group-title">必須處理</h3><article className="task-card urgent"><div className="task-icon"><Icon name="sparkle"/></div><div><span className="badge red">尚未完成</span><h3>Visit Japan Web</h3><p>航班與第一晚酒店資料已準備，可以逐項複製。</p><button onClick={()=>toast("已複製酒店郵政編碼 100-0005")}>開始填寫</button></div></article><h3 className="group-title">旅程文件</h3><div className="document-grid"><article><Icon name="plane"/><strong>機票</strong><span>2 份・已完成</span></article><article><Icon name="hotel"/><strong>酒店</strong><span>1 份・已辨認</span></article><article><Icon name="shield"/><strong>旅遊保險</strong><span>尚未上傳</span></article><article><Icon name="map"/><strong>離線地圖</strong><span>出發前3日提醒</span></article></div><h3 className="group-title">準備清單</h3><div className="check-list">{["檢查護照有效期","購買旅遊保險","準備日圓現金","下載電子門票"].map((x,i)=><button key={x} onClick={(e)=>e.currentTarget.classList.toggle("done")} className={i<2?"done":""}><span><Icon name="check" size={15}/></span>{x}</button>)}</div></section>}

    {active==="行程"&&<section className="screen-content"><div className="page-title"><div><p>10月12日 — 10月18日</p><h2>每日行程</h2></div><button className="round-add" onClick={()=>toast("新增行程項目")}><Icon name="plus"/></button></div><div className="date-strip">{["12 一","13 二","14 三","15 四","16 五"].map((d,i)=><button key={d} className={i===1?"selected":""}><strong>{d.split(" ")[0]}</strong><span>{d.split(" ")[1]}</span></button>)}</div><section className="day-section itinerary-panel"><div className="section-heading day-heading"><div><p>東京・3項安排</p><h3>第二日</h3></div><button className="recommend-button" onClick={()=>toast("正在按酒店位置搜尋")}><Icon name="pin" size={16}/>附近推介</button></div><Timeline/></section><article className="recommend-card"><span className="recommend-visual"><Icon name="sparkle"/></span><div><span>酒店附近推介</span><h3>濱離宮恩賜庭園</h3><p>步行18分鐘・今日開放至17:00</p></div><button onClick={()=>toast("已加入想去地點")}><Icon name="plus" size={18}/></button></article></section>}

    {active==="記帳"&&<section className="screen-content"><div className="page-title"><div><p>2026 東京之旅</p><h2>旅行記帳</h2></div><button className="round-add coral" onClick={()=>pick("receipt")}><Icon name="camera"/></button></div><section className="budget-panel"><p>旅程預算餘額</p><h3>HK$16,420</h3><div><span>已用 HK$3,580</span><span>預算 HK$20,000</span></div><div className="budget-track"><span/></div></section><div className="stat-row"><article><span>今日支出</span><strong>¥8,420</strong></article><article><span>待分帳</span><strong>HK$860</strong></article></div><h3 className="group-title">支出分類</h3><div className="category-list">{[["飲食","HK$1,240","42%"],["交通","HK$690","24%"],["門票","HK$950","32%"]].map(x=><div key={x[0]}><span>{x[0]}</span><i><b style={{width:x[2]}}/></i><strong>{x[1]}</strong></div>)}</div><div className="section-heading expenses-title"><h3>最近帳目</h3><button onClick={()=>toast("顯示全部帳目")}>查看全部</button></div><div className="expense-list"><article><span className="expense-icon">🍣</span><div><strong>築地壽司</strong><small>今日 10:42・平均分帳</small></div><b>¥6,600</b></article><article><span className="expense-icon">🚇</span><div><strong>Suica 增值</strong><small>昨日・個人消費</small></div><b>¥5,000</b></article></div></section>}

    {active==="設定"&&<section className="screen-content"><div className="page-title"><div><p>個人帳戶</p><h2>設定</h2></div></div><article className="profile-card"><span>MT</span><div><strong>Man Tat Ho</strong><p>Google 帳戶已連接</p></div><button><Icon name="edit" size={19}/></button></article><h3 className="group-title">資料與同步</h3><div className="settings-list"><button onClick={()=>toast("所有資料已同步")}><span className="setting-icon blue"><Icon name="cloud"/></span><div><strong>雲端同步</strong><small>剛剛完成・Supabase Free</small></div><span className="status-ok">正常</span></button><button onClick={()=>toast("文件已使用 126 MB / 1 GB")}><span className="setting-icon coral"><Icon name="upload"/></span><div><strong>文件儲存</strong><small>126 MB / 1 GB</small></div><Icon name="arrow" size={18}/></button><button onClick={()=>toast("正在準備旅程備份")}><span className="setting-icon gold"><Icon name="download"/></span><div><strong>匯出備份</strong><small>下載行程、帳目及文件清單</small></div><Icon name="arrow" size={18}/></button><button onClick={()=>toast("私人文件只有你可以查看")}><span className="setting-icon green"><Icon name="shield"/></span><div><strong>私隱與權限</strong><small>同行者及文件分享設定</small></div><Icon name="arrow" size={18}/></button></div><p className="version-note">旅記 TripLog・介面原型 v0.1</p></section>}

    <nav className="bottom-nav" aria-label="主要導覽">{[{label:"首頁",icon:"home"},{label:"準備",icon:"check"},{label:"行程",icon:"calendar"},{label:"記帳",icon:"wallet"},{label:"設定",icon:"user"}].map(i=><button key={i.label} className={active===i.label?"active":""} onClick={()=>setActive(i.label)}><Icon name={i.icon as IconName} size={21}/><span>{i.label}</span></button>)}</nav>
    {notice&&<div className="toast" role="status">{notice}</div>}

    {modal&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setModal(null)}><section className="upload-modal" role="dialog" aria-modal="true" aria-label={modal==="ticket"?"上傳機票":"拍攝收據"} onMouseDown={e=>e.stopPropagation()}><div className="modal-handle"/><button className="modal-close" onClick={()=>setModal(null)}><Icon name="close"/></button><span className={`modal-icon ${modal}`}><Icon name={modal==="ticket"?"plane":"receipt"} size={30}/></span><h2>{modal==="ticket"?"上傳機票建立旅程":"拍攝收據自動入帳"}</h2><p>{modal==="ticket"?"支援機票相片、截圖及 PDF。辨認後會先讓你確認。":"系統會辨認商戶、日期、金額與貨幣，再詢問是否分帳。"}</p><input ref={fileRef} type="file" accept={modal==="ticket"?"image/*,.pdf":"image/*"} capture={modal==="receipt"?"environment":undefined} hidden onChange={e=>setPicked(e.target.files?.[0]?.name||"")}/><button className="upload-zone" onClick={()=>fileRef.current?.click()}><Icon name={modal==="receipt"?"camera":"upload"}/><strong>{picked|| (modal==="receipt"?"開啟相機／選擇相片":"選擇機票檔案")}</strong><span>{picked?"已準備辨認":"資料不會在確認前正式儲存"}</span></button>{picked&&<button className="confirm-button" onClick={()=>{setModal(null);toast(modal==="ticket"?"已讀取機票，準備建立東京旅程":"已讀取收據，請確認金額 ¥6,600")}}>開始自動辨認</button>}</section></div>}
  </div></main>
}
